In [1]:
#Importing Libraries
import numpy as np
import pandas as pd

In [2]:
#Importing DataSets
datasets = pd.read_csv('Data.csv')
x = datasets.iloc[:, :-1].values
x

#print(datasets)

array([[   47, 25000],
       [   45, 26000],
       [   46, 28000],
       [   47, 25000],
       [   45, 22000],
       [   47, 49000],
       [   18, 82000],
       [   29, 80000],
       [   46, 23000],
       [   45, 22000]], dtype=int64)

In [3]:
y = datasets.iloc[:, -1].values
y

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [4]:
print(datasets)

   Age  Salary  Purchased
0   47   25000          1
1   45   26000          1
2   46   28000          1
3   47   25000          1
4   45   22000          1
5   47   49000          1
6   18   82000          0
7   29   80000          0
8   46   23000          1
9   45   22000          1


In [5]:
#Summarize the datasets
print(datasets.shape)

(10, 3)


In [6]:
#Splitting datasets into Train and Test 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25, random_state=0)


In [7]:
#Feature Scaling
#scaling data on a standard scale of -2 to +2
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train)

[[ 0.49399243 -0.89393989]
 [ 0.49399243 -0.73245397]
 [-2.02937431  1.52834884]
 [-1.00133601  1.44760589]
 [ 0.68090848 -0.77282545]
 [ 0.68090848 -0.77282545]
 [ 0.68090848  0.19609004]]


In [8]:
#training
#25% of data is for training purpose
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [9]:
#evaluation
#remaining data into testing func
y_pred = model.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
#in output first column is predicted result and second is actual result

[[1 1]
 [1 1]
 [1 1]]


In [10]:

#accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix: ")
print(cm)

print("Accuracy of the model: {0}%".format(accuracy_score(y_test, y_pred)
*100))

Confusion Matrix: 
[[3]]
Accuracy of the model: 100.0%


In [11]:
#prediction
age = int(input("Enter New Customer's age: "))
sal = int(input("Enter New Customer's Salary: "))
newCust = [[age, sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result == 1:
    print("Customer will buy!")
else: 
    print("Customer won't buy!")